# --- GhostlyPath Configuration ---

# Should the plugin save items in a ghost on death?
# If false, items will drop as usual.
save-items-in-ghost: true

# The distance (in blocks) from a ghost at which it will return items to the owner.
retrieve-distance-blocks: 2.5

# When enabled, a player's compass will point to their most recent death location.
enable-compass-tracking: false

# --- Despawn Settings ---
# A ghost will despawn after this many game ticks (1/20th of a second) of being inside a
# loaded, entity-processing chunk. The timer pauses if the chunk is unloaded.
# Default: 6000 ticks = 5 minutes of being loaded.
# Set to 0 to disable this type of despawning.
ghost-timeout-ticks: 6000

# --- Looting Settings ---
looting:
  # Can OTHER players loot items from a ghost?
  # If false, only the owner can ever retrieve the items.
  allow-looting-by-others: true

  # The time (in seconds) that ONLY the owner can pick up their items.
  # After this time, if 'allow-looting-by-others' is true, anyone can take the items.
  owner-only-duration: 3600 # 10 minutes

# --- Messages (Formatted with MiniMessage) ---
# Learn more at: https://docs.adventure.kyori.net/minimessage/format.html
messages:
  death-location-set: "<#C3FBD8>Ваши вещи в безопасности. Призрак ждет вас."
  compass-not-enabled: "<#C3FBD8>Ваши вещи сохранены призраком."
  ghost-retrieved: "<#DEF7FE>Вы подобрали свои вещи!"
  items-dropped-full-inv: "<#FED6BC>Инвентарь был полон, часть вещей выпала."
  ghost-timed-out: "<#F2B6A0>Ваш призрак растаял вместе с вещами."
  looted-by-other: "<#C3FBD8>Вы собрали вещи <#EAEAEA>%player_name%</#EAEAEA>."
  owner-looted-notification: "<#F2B6A0>Ваши вещи подобрал <#EAEAEA>%looter_name%</#EAEAEA>."
  not-your-ghost: "<#E7ECFF>Этот призрак ждет другого."
  owner-protection-active: "<#FED6BC>Призрак еще защищен: <#E7ECFF>%time%</#E7ECFF>"
  config-reloaded: "<#DEF7FE>Конфиг GhostlyPath перезагружен."
  no-permission: "<#E7ECFF>У вас нет прав для этой команды."